-- Quick passwordless login tokens.
--
-- A small server-side ledger of single-use, time-bounded tokens issued
-- to an existing user. Whoever opens a link containing such a token is
-- logged in as that user without ever supplying the user's API key.
-- Tokens are opaque random strings (~256 bits) generated by the
-- backend; we never store the API key alongside.
--
-- Lifecycle:
--   * created_at  - when the link was generated
--   * expires_at  - hard ISO-8601 cutoff after which the token is dead
--   * consumed_at - set the moment the token is exchanged for a session
--                   (single-use; a second exchange always fails)
CREATE TABLE IF NOT EXISTS magic_login_tokens (
    token        TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at   TEXT NOT NULL,
    expires_at   TEXT NOT NULL,
    consumed_at  TEXT
);

CREATE INDEX IF NOT EXISTS idx_magic_login_tokens_user
    ON magic_login_tokens(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_magic_login_tokens_expires
    ON magic_login_tokens(expires_at);
